apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xxx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jduimovich0/bootstrap:343d6dec90a885ce1f3ffd320ea9e7280db24b80@sha256:927389c4700ad5a27bdf2e08a45af17355b3f28cc93d43cf8baf905b4d1f2c63
          name: container-image
