apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: xxx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xxx 
  name: xxx
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: xxx
    weight: 100 
